/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRoll() {
        int[] rolls = Library.roll(4);
        assertEquals("rolled number:",4, rolls.length);
    }

    @Test public void testContainsDuplicates(){
        int[] Arr ={3,3,4,5,7,8};
        assertTrue("There are duplicates", Library.containsDuplicates(Arr));
    }

    @Test public void testAvg() {
        int[] Arr = {1,2,3,4,5,6};
        double avg = Library.Avg(Arr);
        assertTrue("Avg is:", avg == 3.5);
    }

    @Test public void testArrayAvgValue() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int [] test =weeklyMonthTemperatures[2];
        int [] result = Library.arrAvg(weeklyMonthTemperatures);
        assertEquals("Test should equal:", test, result);
    }

    @Test public void testWeather(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String data=Library.Weather(weeklyMonthTemperatures);
        assertEquals("The String is : ","High: 72\n" + "Low: 51\n" + "Never saw temperature: 63\n" + "Never saw temperature: 67\n" + "Never " +
                "saw temperature: 68\n" + "Never saw temperature: 69\n", data);
    }


    @Test public void testTally(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = Library.tally(votes);
        assertEquals("Winner is: ", "Bush", Library.tally(votes));
    }


}
