/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;


public class App {
    public static void main(String[] args) {
        Path path = Paths.get("./app/src/main/resources/test3.js");
        System.out.println(Linter(path));
    }

    public static String Linter(Path path){
        String msg="";
        BufferedReader reader = null;
        try {
            reader = Files.newBufferedReader(path);
            String line = reader.readLine();
            int count=1;
            while(line != null){

                if(!line.endsWith(";") && !line.isEmpty() && !line.endsWith("{") && !line.endsWith("}") && !line.contains("if") && !line.contains("else")){
                    msg=msg+"Line " + count + ": Missing semicolon."+"\n";
                }
                count++;
                line = reader.readLine();
            }
        } catch (IOException ex){
            ex.printStackTrace();
        } finally {
            if(reader != null) {
                try {
                    reader.close();
                } catch(IOException e){
                    System.out.println("an error occurred while closing the file");
                }
            }
        }
        return msg;
    }

}

