/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void RestaurantTestToString () {
        Restaurant restaurant=new Restaurant("McDonalds",0,4);
        System.out.println(restaurant.toString());
        assertEquals("Test toString method","name is : McDonalds, average stars : NaN, price category, 4",restaurant.toString());
    }

    @Test public  void  RestaurantTestAddReview(){
        Restaurant restaurant=new Restaurant("McDonalds",0,4);
        Review newReview = new Review("ummm its perfect and woow", "Mohamad Alkhateeb",1);
        restaurant.addReview(newReview);
        assertEquals("Mohamad Alkhateeb, 1, ummm its perfect and woow",newReview.toString());
    }

    @Test public  void  ShopTestAddReview(){
        Shop Shop=new Shop("McDonalds","Nide place","21$");
        Review newReview = new Review("ummm its perfect and woow", "Mohamad Alkhateeb",1);
        Shop.addReview(newReview);
        assertEquals("Mohamad Alkhateeb, 1, ummm its perfect and woow",newReview.toString());
    }

    @Test public  void  TheaterTestAddReview(){
        Theater Theater=new Theater("Masrah Masr");
        Review newReview = new Review("ummm its perfect and woow", "Mohamad Alkhateeb",1);
        Theater.addReview(newReview);
        assertEquals("Mohamad Alkhateeb, 1, ummm its perfect and woow",newReview.toString());
    }

    @Test public  void  TheaterTestAddReview2(){
        Theater Theater=new Theater("Masrah Masr");
        Review newReview = new Review("ummm its perfect and woow", "Mohamad Alkhateeb",1,"Masrah Masr");
        Theater.addReview(newReview);
        assertEquals("Mohamad Alkhateeb, 1, ummm its perfect and woow",newReview.toString());
    }


}
