/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {


    @Test public void testLinter() {
        Path test1 = Paths.get("./src/main/resources/test1.js");
        Path test2 = Paths.get("./src/main/resources/test2.js");
        Path test3 = Paths.get("./src/main/resources/test3.js");
        Path test4 = Paths.get("./src/main/resources/test4.js");
        Path test5 = Paths.get("./src/main/resources/test5.js");

        String test1Ex ="";
        String test2Ex ="Line 5: Missing semicolon.\n";
        String test3Ex ="Line 13: Missing semicolon.\n" +
                "Line 32: Missing semicolon.\n" +
                "Line 40: Missing semicolon.\n" +
                "Line 51: Missing semicolon.\n" +
                "Line 59: Missing semicolon.\n" +
                "Line 60: Missing semicolon.\n" +
                "Line 61: Missing semicolon.\n" +
                "Line 62: Missing semicolon.\n";
        String test4Ex ="Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 11: Missing semicolon.\n" +
                "Line 13: Missing semicolon.\n" +
                "Line 15: Missing semicolon.\n" +
                "Line 26: Missing semicolon.\n" +
                "Line 28: Missing semicolon.\n" +
                "Line 32: Missing semicolon.\n" +
                "Line 36: Missing semicolon.\n" +
                "Line 40: Missing semicolon.\n" +
                "Line 41: Missing semicolon.\n" +
                "Line 50: Missing semicolon.\n" +
                "Line 51: Missing semicolon.\n" +
                "Line 59: Missing semicolon.\n" +
                "Line 60: Missing semicolon.\n" +
                "Line 61: Missing semicolon.\n" +
                "Line 62: Missing semicolon.\n" +
                "Line 64: Missing semicolon.\n" +
                "Line 70: Missing semicolon.\n" +
                "Line 71: Missing semicolon.\n" +
                "Line 72: Missing semicolon.\n" +
                "Line 73: Missing semicolon.\n" +
                "Line 74: Missing semicolon.\n" +
                "Line 76: Missing semicolon.\n" +
                "Line 77: Missing semicolon.\n" +
                "Line 78: Missing semicolon.\n" +
                "Line 79: Missing semicolon.\n" +
                "Line 80: Missing semicolon.\n" +
                "Line 82: Missing semicolon.\n" +
                "Line 83: Missing semicolon.\n" +
                "Line 84: Missing semicolon.\n" +
                "Line 85: Missing semicolon.\n" +
                "Line 86: Missing semicolon.\n" +
                "Line 88: Missing semicolon.\n" +
                "Line 89: Missing semicolon.\n" +
                "Line 90: Missing semicolon.\n" +
                "Line 91: Missing semicolon.\n" +
                "Line 92: Missing semicolon.\n" +
                "Line 94: Missing semicolon.\n" +
                "Line 95: Missing semicolon.\n" +
                "Line 96: Missing semicolon.\n" +
                "Line 97: Missing semicolon.\n" +
                "Line 98: Missing semicolon.\n" +
                "Line 99: Missing semicolon.\n" +
                "Line 100: Missing semicolon.\n" +
                "Line 101: Missing semicolon.\n";
        String test5Ex ="";

        assertEquals("Test 1 Result",test1Ex,App.Linter(test1));
        assertEquals("Test 2 Result",test2Ex,App.Linter(test2));
        assertEquals("Test 3 Result",test3Ex,App.Linter(test3));
        assertEquals("Test 4 Result",test4Ex,App.Linter(test4));
        assertEquals("Test 5 Result",test5Ex,App.Linter(test5));

    }


}
